services:
  whatsapp-dimas:
    image: 'registry.hom.lan/whatsapp-dimas:latest'
    container_name: 'whatsapp-dimas'
    restart: always
    networks:
      - deploy_devnet
    #ports:
    #  - 3013:3000
    env_file:
      - ./.env
    volumes:
      - ./dbs:/usr/app/gowam-rest/dbs
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.whatsapi.rule=Host(`whatsapi.hom.lan`)"
      - "traefik.http.routers.whatsapi.entrypoints=websecure"
      - "traefik.http.routers.whatsapi.tls=true"
      - "traefik.http.services.whatsapi.loadbalancer.server.port=3000"

networks:
  deploy_devnet:
    external: true